### ISSUE TITLE
P3-Project_Planning

### ISSUE THREAD

**Issue by jameslyleyoung** [cfiller123/liftoff-assignments#3]
User Stories:  Your user stories aren't structured correctly. All user stories should be in this format: [define user][define action]**[justification]**.

Like on this one, "As a user, I can fill out a form and save my court watching data in a persistent database."  You would need to add your justification.  
As a user,
I can save my court watching data,
So that ...??
You could put in, something about so I can go back and review it before submitting, or something else from the user's perspective.

You still get a complete, as you have obviously put time and effort into your project, which-as I've said-is the most important part of Liftoff and the Apprenticeship program anyway.

**Comment by cfiller123** [comment]
Ok, fixed this. Thanks!
